---
title: "FinalProjectQ2"
author: "Kathryn Stoven"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(readxl)
library(tidyverse)
library(car)
```

## Dataset
```{r}
supply <- read_excel("Cleaned_Supply_Chain_Data.xlsx")
names(supply)
str(supply)
```

# Basic data cleaning and EDA
```{r}
# Convert necessary categorical variables to factors
supply <- supply %>%
  mutate(
    Supplier.name = as.factor(Supplier.name),
    Transportation.modes = as.factor(Transportation.modes),
    Product.type = as.factor(Product.type)
  )

str(supply)
```

```{r}
# Keep only necessary variables
q2_data <- supply %>%
  select(Transportation.modes, Product.type, Defect.rates) %>%
  drop_na()

# Check counts per cell (important for balanced vs unbalanced design)
table(q2_data$Transportation.modes, q2_data$Product.type)
```
```{r}
# Descriptive statistics table
q2_summary <- q2_data %>%
  group_by(Transportation.modes, Product.type) %>%
  summarise(
    n = n(),
    mean_defect = mean(Defect.rates),
    sd_defect = sd(Defect.rates),
    .groups = "drop"
  )

q2_summary
```

# QUESTION 2: Two-way ANOVA Model
Research Question:
Do transportation mode and product type interact to affect defect rates?
DV = Defect.rates (numeric)
IV1 = Transportation.modes (categorical)
IV2 = Product.type (categorical)

```{r}
# Two-way ANOVA with interaction (Unbalanced)

q2_model <- lm(Defect.rates ~ Transportation.modes + Product.type + Transportation.modes * Product.type, data = q2_data)
Anova(q2_model, type = "II")

```

## QUESTION 2: Interaction Plot
```{r}
# Interaction plot
interaction.plot(
  x.factor = q2_data$Transportation.modes,
  trace.factor = q2_data$Product.type,
  response = q2_data$Defect.rates,
  fun = mean,
  ylab = "Mean Defect Rate",
  xlab = "Transportation Mode",
  trace.label = "Product Type",
  main = "Interaction Plot: Transportation Mode and Product Type"
)
```
```{r}
# Follow-up analysis because interaction is significant
air_data <- q2_data %>%
  filter(Transportation.modes == "Air")

air_model <- aov(Defect.rates ~ Product.type, data = air_data)
summary(air_model)
TukeyHSD(air_model)
```

```{r}

rail_data <- q2_data %>% filter(Transportation.modes == "Rail")
road_data <- q2_data %>% filter(Transportation.modes == "Road")
sea_data  <- q2_data %>% filter(Transportation.modes == "Sea")

summary(aov(Defect.rates ~ Product.type, data = rail_data))
summary(aov(Defect.rates ~ Product.type, data = road_data))
summary(aov(Defect.rates ~ Product.type, data = sea_data))
```

